### ISSUE TITLE
The Simplified Chinese version of codelab does not have a corresponding source code

### ISSUE THREAD

**Issue by pdog18** [android/codelab-android-compose#255]
The Simplified Chinese version of codelab does not have a corresponding source code

The English version was last updated on May 16, 2022 and the Simplified Chinese version was last updated on February 24, 2022.

I suggest that unless the codelab in different languages can be updated at the same time, it is better to leave only the correct (latest) version.

**Comment by luanrz** [comment]
other languages have similar problems
