### ISSUE TITLE
BasicLayoutsCodelab does not use Material 3

### ISSUE THREAD

**Issue by matej-marjanovic** [android/codelab-android-compose#364]
Starting a new empty Android project using compose will use Material 3 by default. 
The BasicLayoutsCodelab is still designed around the previous version of Material.

For example, it seems that Material 3 does not have "BottomNavigation" but it has "NavigationBar".
It is surprising to go through the codelab and not being able to apply it on a default project without reverting the default to what I understand is the previous version of the material library.

**Comment by JolandaVerhoef** [comment]
It was updated recently, see https://github.com/android/codelab-android-compose/pull/371
