### ISSUE TITLE
[NavigationCodelab] end branch is missing the navigation testing dependency.

### ISSUE THREAD

**Issue by easyhooon** [android/codelab-android-compose#365]
To make the test code succeed as in the codelab, end branch needs to add the following dependency in the build.gradle: androidTestImplementation "androidx.navigation:navigation-testing:$rootProject.composeNavigationVersion". 

Otherwise, the following error will occur: 

e: file:///Users/yijihun/AndroidStudioProjects/codelab-android-compose/NavigationCodelab/app/src/androidTest/java/com/example/compose/rally/NavigationTest.kt:26:28 Unresolved reference: testing

'e: file:///Users/username/AndroidStudioProjects/codelab-android-compose/NavigationCodelab/app/src/androidTest/java/com/example/compose/rally/NavigationTest.kt:36:33 Unresolved reference: TestNavHostController'.

e: file:///Users/yijihun/AndroidStudioProjects/codelab-android-compose/NavigationCodelab/app/src/androidTest/java/com/example/compose/rally/NavigationTest.kt:42:29 Unresolved reference: TestNavHostController

**Comment by simona-anomis** [comment]
Thanks @easyhooon , fixed in https://github.com/android/codelab-android-compose/pull/506
