### ISSUE TITLE
Why Camel Casing is used for variable names ?

### ISSUE THREAD

**Issue by ankursamarya** [android/codelab-android-compose#379]
In ThemingCodelab/app/src/main/java/com/example/reply/ui/theme/Color.kt file `Purple80 etc.`  used Camel Casing
```
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
```

In ThemingCodelab/app/src/main/java/com/example/reply/ui/theme/Type.kt file `Typography` used Camel Casing
```
val Typography = Typography(
    ...
    ...
    )
```

Please elaborate on the naming conventions. Thanks

**Comment by riggaroo** [comment]
You can find more information about this here - https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#singletons-constants-sealed-class-and-enum-class-values
