### ISSUE TITLE
[BasicsLayoutCodelab][Step 4]: Deprecated feature usage

### ISSUE THREAD

**Issue by asensiodev** [android/codelab-android-compose#425]
Hi,

In [Basics Layouts in compose](https://developer.android.com/codelabs/jetpack-compose-layouts?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fjetpack-compose-for-android-developers-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fjetpack-compose-layouts#3) codelab step 4, **TextFieldDefaults.textFieldColors** is being used but is currently deprecated, I think **TextFieldDefaults.colors** should be used instead, as is being done in the code snippet of the same codelab. I attach the image:

![ss](https://github.com/android/codelab-android-compose/assets/48333020/4a37a78e-ac1c-4195-91c2-dfff9486a33a)

**Comment by simona-anomis** [comment]
Fixed, thanks @asensiodev
