### ISSUE TITLE
Repository clone mistake

### ISSUE THREAD

**Issue by alexstivi** [android/codelab-android-compose#441]
Hello,
Repository is not clonning with folowing response:
Cloning into 'codelab-android-compose'...
remote: Enumerating objects: 12223, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (56/56), done.
error: 3230 bytes of body are still expected MiB | 718.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

os: linux ubuntu

**Comment by MohammedKhudair** [comment]
Yes, same issue !
