### ISSUE TITLE
[AdvancedStateAndSideEffectsCodelab] Cannot build project

### ISSUE THREAD

**Issue by tigerlily777** [android/codelab-android-compose#481]
.../AdvancedStateAndSideEffectsCodelab/app/src/main/java/androidx/compose/samples/crane/details/DetailsActivity.kt:159:29
None of the following candidates is applicable:
suspend fun MapFragment.awaitMap(): GoogleMap
suspend fun MapView.awaitMap(): GoogleMap
suspend fun SupportMapFragment.awaitMap(): GoogleMap

.../AdvancedStateAndSideEffectsCodelab/app/src/main/java/androidx/compose/samples/crane/details/DetailsActivity.kt:160:19 Cannot inline bytecode built with JVM target 17 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option.

I assume the dependencies lib below is built with JVM target 17? 
    implementation "com.google.android.libraries.maps:maps:3.1.0-beta"
Do we have an updated lib that built with 18?

**Comment by simona-anomis** [comment]
Cannot reproduce
